### ISSUE TITLE
Please publish the current code version to rubygems

### ISSUE THREAD

**Issue by lmmendes** [emartech/escher-rack_middleware-ruby#2]
Since @miguelverissimo  pull request got merged with master, Emarsys didn't release a new version of this gem.

As i need the `include_path` feature I'm requiring this code directly from the git repository as you can see in the code bellow; Bundler _seems to have_ a bug that he doesn't respect the gem declaration order and first requires the gems fetched via local or git repositories.

Since `escher-rack_middlerware` requires inside its code `escher` (the `echer-ruby` gem) bundler breaks.

You can test the behaviour following this steps:

1 Create a `Gemfile` with the following content:

``` ruby
source "https://rubygems.org"

# gem "rails"
gem "escher"
gem 'escher-rack_middleware', require: 'escher/rack_middleware', 'git@github.com:emartech/escher-rack_middleware-ruby.git
```

2 Then create a ruby script with the following content, eg: `test.rb`

``` ruby
require 'bundler'
Bundler.require(:default)
```

3 Run the script

```
$ bundler
$ ruby test.rb
```

> Please do a `gem list` and remove `escher` and `escher-rack_middleware` from your sistem using `gem uninstall <gem name>`  if you have already them installed.

If everything goes according to planned you will probably see the following error:

``` bash
here was a LoadError while loading escher-rack_middleware.gemspec:
cannot load such file -- escher from
  /servers/sites/backend-saas/shared/bundle/ruby/2.1.0/bundler/gems/escher-rack_middleware-ruby-aa2991709e5f/escher-rack_middleware.gemspec:4:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.
```

This happens because I'm requiring `escher-rack_middleware` gem from a git repository, bundler ignores the declaration order inside the `Gemfile` and fetches first the code from the git repos and requires them first.

Knowing that, would be nice if you release a new version of the gem, with the `master` branch code.

> NOTE: There is a way to circumvent this situation that is requiring `escher` ruby also as a git repository but that's not the "ruby" way and that way you have a gem inside ruby gems updated.

**Comment by lmmendes** [comment]
@adamluzsi can you provided any feedback regarding this issue?

**Comment by adamluzsi** [comment]
Dear Immendes, sorry to keep you wait , the issue will be handled today and the new version will be released as soon as possible , while the gemspec will get a fix too. 

Best regards, 
Adam

**Comment by adamluzsi** [comment]
The update has been made, but please keep in mind, that the released version support both include and exclude at once. This is due to support the include paths that are overlapping the excluded paths registered with regular expression.

The most commonly used pattern for limiting an API access with auth logic, is to use the middleware in that controller. For example, if you use [rack-app](http://www.rack-app.com) you can use the following syntax:

``` ruby

class ProtectedAPI < Rack::App 

  middleware do |builder|
    builder.use Escher::RackMiddleware
  end

  get '/my/protected/endpoint_path' do 
    "OK"
  end

end

```

And mount that protected api to your main application. 
This is pretty common in almost every framework with a few exception.
If you use Rails then you can use the "around" action to mimic middleware behavior and just initialize the middleware  and call it with the env to proxy valid auth calls to the controller. 

If you don't want to use this pattern, you can still exclude every path with regular expression and include only those that you want to authenticate, but this should be only a temporary workaround for long term.

Hope the new release serve you in your work! :) 

Best regards,
Adam L.

**Comment by adamluzsi** [comment]
with the version 0.3.1 that include the requested feature, I close the issue, if you still have any thought, please don't hesitate to share with us!
